### ISSUE TITLE
PA Review: Initial Proposal

### ISSUE THREAD

**Issue by avelasco920** [avelasco920/stocks-overflow#1]
- [x] Replace `Data Visualization` to `News` in [MVPs list](https://github.com/avelasco920/StockOverflow/wiki/mvp-list)
- [x] Further develop CRUD routes. Consider user interactions with stock (buy a stock, watch a company, fetch news)
- [x] Consolidate user information in Sample State. Currently displaying excess information
- [x] Add `NewsArticle` table in schema

**Comment by anastassia-b** [comment]
Your proposal has been approved. Thank you for taking into account these changes!
