### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by avelasco920** [avelasco920/stocks-overflow#2]
* [ ] Backend: DB, model, controller, views
* [ ] Redux Loop: ajax, actions, reducer
* [ ] Presentational Components
* [ ] Styling
* [ ] Smooth, bug-free navigation
* [ ] Adequate and appropriate seeds

**Comment by avelasco920** [comment]
completed user auth with both signin and signup fully styled. demo user created and ability to sign in as demo user on both pages.

**Comment by anastassia-b** [comment]
Excellent work! Account creation and sign in works, the styling is impeccable, and errors do not persist when switching between login/signup. Very intuitive and engaging UI.
