### ISSUE TITLE
PA Review: Companies

### ISSUE THREAD

**Issue by avelasco920** [avelasco920/stocks-overflow#5]

**Comment by anastassia-b** [comment]
This feature is coming along nicely. Here is what we discussed today: 
- [ ] Completing the "watch" functionality, by returning the company from the db request, dispatching an action which updates the is_following? to true. 
- [ ] Adding a toggle function to the company bio by adding state to the AboutCompany component and passing as the css class on the biography element 

Will there be a corresponding view regarding the companies a user is watching? Do you plan a selected feed, or something on the Account page, or does it not affect any view?

**Comment by anastassia-b** [comment]
Excellent work. Swapping the watch icon from the news to the company was a good design choice. The functionality is flawless, this MVP is complete.
